name: neural-networks
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter
  - numpy>=1.26
  - pandas>=2.2
  - matplotlib>=3.8
  - pytorch>=2.4
  - torchvision>=0.17
  - pillow>=10.0
  - scikit-learn>=1.3
  - openpyxl>=3.1.5